language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules

install:
  - npm install
  - npm run init

script:
  - npm run test-coverage

after_success:
  - npm run report-coverage

notifications:
  email:
    on_success: never
    on_failure: always
