language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

install:
  - npm install
  - npm run init

env:
  - NODE_ENV=test DATABASE_URL_TEST=postgres://postgres@localhost:5432/per_org_test

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE per_org_test;' -U postgres

script:
  - npm run test-coverage

after_success:
  - npm run report-coverage

notifications:
  email:
    on_success: never
    on_failure: always
